# Generated by Django 4.0 on 2022-03-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaiportfolioform',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='jaiportfolioform',
            name='subject',
            field=models.CharField(max_length=50),
        ),
    ]
